### ISSUE TITLE
[BUG] Checks off Cloth and Rope after getting the checks but not the actual items

### ISSUE THREAD

**Issue by ZSlyzer** [TopazTK/TrackKH#4]
TrackKH Version:
v0.60 - BETA

Operating System:
Windows x64 (Windows 11)

Tracking Mode:
Automatic

Bug Description:
When getting the Cloth and Rope checks, it checks off the items on the tracker but they are actually not in your inventory.

Reproduction Steps:
- Go to Destiny Islands Day 1 and get the Cloth and Rope checks
- Full restart of game might be necessary

Screenshots/Video:
https://www.youtube.com/watch?v=YXX_7ErdKMU&ab_channel=Slyzer

**Comment by TopazTK** [comment]
Fixed as of 0a21f8c1b989951af86b9bc1304b2385d13fcf64
Closing.
